#########################################
# Config Map variable
#########################################

variable "config" {
  type = "map"

  default {}
}


#########################################
# Standard Variables
#########################################

variable "region" {
  description = "The AWS region which this virtual machine will be provisioned into."
  default = "ap-southeast-2"
  type = "string" 
}

variable vm_count {
  description = "How many virtual machines are to be provisioned"
  type = "string" 
}

variable os {
  description = "Operating systems to deploy; valid options are \"windows\" or \"linux\""
  default = "windows"
  #default = "linux"
  type = "string" 
}

variable "dnssuffix" {
  description = "The dnssuffix which will be used when calling Chef/Puppet, this is required in order to properly sign the server certificate: TODO - set default to be autogenerated from provider"
  default = ""
  type = "string" 
}

variable environment {
  default = "dev"
  type = "string" 
}

variable "instance_type" {
  description = "The AWS EC2 instance type to use; defaults to \"t2.micro\""
  type = "string" 
	default = "t2.micro"
}

variable "name" {
  default = ""
}

variable "vpc_security_group_ids" {
  default = ""
}

variable "ami_name" {
  type = "map"

  default = {
    windows = "Windows_Server-2016-English-Full-Base-*"
    linux = "unknown CentOS 7 (x86_64) - with Updates HVM*"
  }
}